# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|
  config.vm.box = "debian/buster64"
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 443, host: 4443
  config.vm.network "private_network", ip: "172.16.0.10", virtualbox__intnet: "visio"
  # config.vm.network "public_network"
  # config.vm.synced_folder "../data", "/vagrant_data"

  config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
    vb.memory = "1024"
  end
  config.vm.provision "shell", path: "bootstrap.sh"
  # config.vm.provision "file", source: "./haproxy.cfg", destination: "/tmp/haproxy.cfg"
  config.vm.provision "shell", inline: "sudo cp -f /vagrant/haproxy.cfg /etc/haproxy/haproxy.cfg"
  config.vm.provision "shell", inline: "sudo systemctl reload haproxy"
 
end
